fs   = require 'fs'
path = require 'path'
Yang = require './yang'

schema = fs.readFileSync (path.resolve __dirname, '../yang-language.yang'), 'utf-8'
module.exports =
  new Yang schema,
    extension: [
      require './extension/module'
      require './extension/action'
      require './extension/anydata'
      require './extension/argument'
      require './extension/augment'
      require './extension/belongs-to'
      require './extension/bit'
      require './extension/case'
      require './extension/choice'
      require './extension/config'
      require './extension/container'
      require './extension/default'
      require './extension/deviate'
      require './extension/deviation'
      require './extension/enum'
      require './extension/extension'
      require './extension/feature'
      require './extension/grouping'
      require './extension/identity'
      require './extension/if-feature'
      require './extension/import'
      require './extension/include'
      require './extension/input'
      require './extension/key'
      require './extension/leaf'
      require './extension/leaf-list'
      require './extension/length'
      require './extension/list'
      require './extension/mandatory'
      require './extension/max-elements'
      require './extension/min-elements'
      require './extension/modifier'
      require './extension/module'
      require './extension/must'
      require './extension/notification'
      require './extension/output'
      require './extension/path'
      require './extension/pattern'
      require './extension/prefix'
      require './extension/range'
      require './extension/refine'
      require './extension/require-instance'
      require './extension/revision'
      require './extension/rpc'
      require './extension/status'
      require './extension/submodule'
      require './extension/type'
      require './extension/typedef'
      require './extension/unique'
      require './extension/uses'
      require './extension/when'
      require './extension/yin-element'
    ]
    
    typedef: [
      require './typedef/js-function'
      require './typedef/js-array'
      require './typedef/boolean'
      require './typedef/empty'
      require './typedef/binary'
      require './typedef/integer'
      require './typedef/decimal64'
      require './typedef/string'
      require './typedef/union'
      require './typedef/enumeration'
      require './typedef/identityref'
      require './typedef/instance-identifier'
      require './typedef/leafref'
    ]

